version: '3'
services:
  consul:
    # image: "hashicorp/consul"
    image: "consul:1.15.4"
    ports:
      - 8500:8500
  mysql:
    image: "mysql:8.0.41"
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Jzx583803@ 